# Generated by Django 4.2.5 on 2023-12-22 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import writing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=30, unique=True, verbose_name='emoji')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Feeling',
                'verbose_name_plural': 'Feeling',
                'db_table': 'user_feeling',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '自动检测'), (2, '图片'), (3, '视频'), (4, '音频'), (5, '其他')], default=1, verbose_name='类型')),
                ('uri', writing.models.MediaFileFiled(upload_to=writing.models.upload_to, verbose_name='媒体文件')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='大小(Bytes)')),
                ('model', models.CharField(choices=[('Moment', '动态')], default='Moment', max_length=20, verbose_name='所属模型')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('extra', models.JSONField(blank=True, default=dict, null=True, verbose_name='其他信息')),
                ('engine', models.IntegerField(choices=[(1, '七牛云'), (2, '本地')], default=1, verbose_name='存储引擎')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '媒体',
                'verbose_name_plural': '媒体',
                'db_table': 'user_media',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='标签名')),
                ('color', models.CharField(blank=True, max_length=32, null=True, verbose_name='颜色')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'user_tag',
                'ordering': ['-id'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_status', models.PositiveIntegerField(choices=[(1, '正常'), (2, '已删除')], default=1, verbose_name='写作状态')),
                ('media_info', models.JSONField(blank=True, default=list, null=True, verbose_name='媒体信息')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='其他信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.CharField(max_length=2000, verbose_name='内容')),
                ('occurred_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='发生时间')),
                ('feeling', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='writing.feeling', verbose_name='心情')),
                ('medias', models.ManyToManyField(blank=True, db_constraint=False, to='writing.media', verbose_name='媒体')),
                ('tags', models.ManyToManyField(blank=True, db_constraint=False, to='writing.tag', verbose_name='标签')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '动态',
                'verbose_name_plural': '动态',
                'db_table': 'user_moment',
                'ordering': ('-occurred_time',),
            },
        ),
    ]
