# Generated by Django 4.2.5 on 2024-05-27 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writing', '0002_thing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeling',
            options={'verbose_name': '感受', 'verbose_name_plural': '感受'},
        ),
        migrations.AddField(
            model_name='thing',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thing',
            name='explain',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='解释'),
        ),
    ]
