# Generated by Django 4.2.5 on 2024-05-29 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_alter_feeling_options_thing_user_alter_thing_explain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='writing.thing', verbose_name='上级'),
        ),
        migrations.CreateModel(
            name='FeelingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('feeling', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='writing.feeling', verbose_name='心情')),
                ('moment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='writing.moment', verbose_name='瞬间')),
                ('thing', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='writing.thing', verbose_name='事情')),
            ],
            options={
                'verbose_name': '事情',
                'verbose_name_plural': '事情',
                'db_table': 'user_feeling_record',
                'ordering': ('-id',),
            },
        ),
    ]
