# Generated by Django 4.2.5 on 2024-05-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_alter_thing_parent_feelingrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feelingrecord',
            options={'ordering': ('-id',), 'verbose_name': '记录', 'verbose_name_plural': '记录'},
        ),
        migrations.AddField(
            model_name='feelingrecord',
            name='notify_time',
            field=models.DateTimeField(default='2024-01-01', unique=True, verbose_name='通知时间'),
            preserve_default=False,
        )
    ]
